; Generated by AutoGUI 2.5.4
#NoEnv
#SingleInstance Force
#InstallKeybdHook

SetWorkingDir %A_ScriptDir%

Menu menuArquivo, Add, &Open...`tCtrl+O, MenuAbrir
Menu menuArquivo, Disable, 1&
Menu menuArquivo, Add, &Sair`tEsc, MenuSair
Menu MenuBar, Add, Arquivo, :menuArquivo
Menu menuAjuda, Add, &Sobre, MenuSobre
Menu MenuBar, Add, &Ajuda, :menuAjuda
Gui Menu, MenuBar

global percentLife1, percentLife2, percentLife3
global x1_lifeBar, x2_lifeBar, y1_lifeBar, y2_lifeBar
global status := 0

global x_txtKey1 := 50
global y_txtKey1 := 63

Gui Font, s15 Bold, Tahoma
Gui Add, Text, x190 y5 w147 h25 +0x200, Rila Desgraça
Gui Font
Gui Add, Text, x50 y43 w33 h23 +Disabled +0x200 vtxtKey1, Key 1:
Gui Add, Text, x50 y80 w33 h23 +Disabled +0x200 vtxtKey2, Key 2:
Gui Add, Text, x50 y117 w33 h23 +Disabled +0x200 vtxtKey3, Key 3:
Gui Add, ComboBox, x94 y43 w55 +Disabled +Uppercase vcbxKey1, F1|F2|F3|F4|F5|F6|F7|F8|F9|F10|F11|F12
Gui Add, ComboBox, x94 y80 w55 +Disabled +Uppercase vcbxKey2, F1|F2|F3|F4|F5|F6|F7|F8|F9|F10|F11|F12
Gui Add, ComboBox, x94 y117 w55 +Disabled +Uppercase vcbxKey3, F1|F2|F3|F4|F5|F6|F7|F8|F9|F10|F11|F12
Gui Add, ComboBox, x195 y43 w136 +Disabled vcbxSpell1, Exura|Exura Gran|Exura Ico|Exura Gran Ico
Gui Add, Text, x162 y43 w30 h23 +Disabled +0x200 vtxtSpell1, Spell:
Gui Add, Text, x162 y80 w30 h23 +Disabled +0x200 vtxtSpell2, Spell:
Gui Add, ComboBox, x195 y80 w136 +Disabled vcbxSpell2, Exura|Exura Gran|Exura Ico|Exura Gran Ico
Gui Add, Text, x162 y117 w30 h23 +Disabled +0x200 vtxtSpell3, Spell:
Gui Add, ComboBox, x195 y117 w136 +Disabled vcbxSpell3, Exura|Exura Gran|Exura Ico|Exura Gran Ico
Gui Add, CheckBox, x28 y43 w15 h23 vCheck1 gCheckBox1
Gui Add, CheckBox, x28 y80 w15 h23 vCheck2 gCheckBox2
Gui Add, CheckBox, x28 y117 w15 h23 vCheck3 gCheckBox3
Gui Add, Text, x14 y197 w55 h23 +0x200, Timer (ms):
Gui Add, Edit, x69 y201 w70 h21 vtimer
Gui Add, Button, x320 y201 w80 h23 +Disabled vstartPause gbtn_Start, &Start
Gui Add, Button, x408 y201 w80 h23 +Disabled, &Save
Gui Add, Button, x145 y201 w70 h21 vbtn_Timer gsetTimer, Set Timer
Gui Add, Slider, x346 y43 w120 h32 +Disabled +Tooltip vsliderLife1 gSlider1Move, 50
Gui Add, Slider, x346 y80 w120 h32 +Disabled +Tooltip vsliderLife2 gSlider2Move, 50
Gui Add, Slider, x346 y117 w120 h32 +Disabled +Tooltip vsliderLife3 gSlider3Move, 50
Gui Add, Edit, x468 y43 w27 h22 +Disabled vedtLife1 gEdit1Modify
Gui Add, Edit, x468 y80 w27 h22 +Disabled vedtLife2 gEdit2Modify
Gui Add, Edit, x468 y117 w27 h22 +Disabled vedtLife3 gEdit3Modify
Gui Add, CheckBox, x28 y154 w15 h23 vcheckParalyze gCheckParalyze
Gui Add, Text, x50 y154 w65 h23 +Disabled +0x200 vtxtParalyze, Anti-Paralyze
Gui Add, ComboBox, x120 y154 w55 +Disabled +Uppercase vcbxKeyParalyze, F1|F2|F3|F4|F5|F6|F7|F8|F9|F10|F11|F12
Gui Add, StatusBar, vstatusBar, Faltar definir a posição inicial e final da vida.
Gui Show, w526 h255, Rila Desgraça
goto verifyVersion
Return

varExist(ByRef v) { ; Requires 1.0.46+
   return &v = &n ? 0 : v = "" ? 2 : 1 
}

verifyVersion:
    UrlDownloadToFile, https://raw.githubusercontent.com/Kanchii/AutoHotkey_HealBot/master/version.txt, version_temp.txt
    FileRead, v_tmp, version_temp.txt
    FileRead, vers, version.txt
    if(v_tmp != vers){
        MsgBox, 0x4, Atualização, Tem uma nova versão disponível. Gostaria de atualizar?, 
        IfMsgBox Yes
            goto UpdateProgram
        else
            FileDelete, version_temp.txt
    } else {
        FileDelete, version_temp.txt
    }
Return

UpdateProgram:
    FileRead, v_ants, version.txt
    UrlDownloadToFile, https://raw.githubusercontent.com/Kanchii/AutoHotkey_HealBot/master/version.txt, version.txt
    FileRead, v_depois, version.txt
    arquivo_Depois := "Rilador_" . v_depois . ".exe"
    UrlDownloadToFile, https://raw.githubusercontent.com/Kanchii/AutoHotkey_HealBot/master/Rilador.exe, % arquivo_Depois
    FileDelete, version_temp.txt
    ExitApp
Return

MenuSair:
    ExitApp
Return

MenuAbrir:
Return

MenuSobre:
    MsgBox, Auto Healer de Tibia, feito com muita gambiarra e amor`n`n`n                                     Criado por Felipe Weiss '-'
Return

^1::
    status |= (1 << 0)
    if(status = 1){
        GuiControl, , statusBar, Falta definir a posição final da vida.
    } else if(status = 3){
        GuiControl, , statusBar, O bot se encontra pausado.
    }

    MouseGetPos, x1_LifeBar, y1_LifeBar
Return

^2::
    status |= (1 << 1)
    if(status = 2){
        GuiControl, , statusBar, Falta definir a posição inicial da vida.
    } else if(status = 3){
        GuiControl, , statusBar, O bot se encontra pausado.
    }
    MouseGetPos, x2_LifeBar, y2_LifeBar
Return

CheckBox1:
    GuiControlGet, Check1
    if(Check1 = 0){
        GuiControl, Disable, txtKey1
        GuiControl, Disable, cbxKey1
        ;GuiControl, Disable, txtSpell1
        ;GuiControl, Disable, cbxSpell1
        GuiControl, Disable, sliderLife1
        GuiControl, Disable, edtLife1
    } else {
        GuiControl, Enabled, txtKey1
        GuiControl, Enabled, cbxKey1
        ;GuiControl, Enabled, txtSpell1
        ;GuiControl, Enabled, cbxSpell1
        GuiControl, Enabled, sliderLife1
        GuiControl, Enabled, edtLife1
    }
Return


CheckBox2:
    GuiControlGet, Check2
    if(Check2 = 0){
        GuiControl, Disable, txtKey2
        GuiControl, Disable, cbxKey2
        ;GuiControl, Disable, txtSpell2
        ;GuiControl, Disable, cbxSpell2
        GuiControl, Disable, sliderLife2
        GuiControl, Disable, edtLife2
    } else {
        GuiControl, Enabled, txtKey2
        GuiControl, Enabled, cbxKey2
        ;GuiControl, Enabled, txtSpell2
        ;GuiControl, Enabled, cbxSpell2
        GuiControl, Enabled, sliderLife2
        GuiControl, Enabled, edtLife2
    }
Return


CheckBox3:
    GuiControlGet, Check3
    if(Check3 = 0){
        GuiControl, Disable, txtKey3
        GuiControl, Disable, cbxKey3
        ;GuiControl, Disable, txtSpell3
        ;GuiControl, Disable, cbxSpell3
        GuiControl, Disable, sliderLife3
        GuiControl, Disable, edtLife3
    } else {
        GuiControl, Enabled, txtKey3
        GuiControl, Enabled, cbxKey3
        ;GuiControl, Enabled, txtSpell3
        ;GuiControl, Enabled, cbxSpell3
        GuiControl, Enabled, sliderLife3
        GuiControl, Enabled, edtLife3
    }
Return

CheckParalyze:
    GuiControlGet, checkParalyze
    if(checkParalyze = 0){
        GuiControl, Disable, txtParalyze
        GuiControl, Disable, cbxKeyParalyze
    } else {
        GuiControl, Enabled, txtParalyze
        GuiControl, Enabled, cbxKeyParalyze
    }
Return

Slider1Move:
    Gui, Submit, nohide
    GuiControl,, edtLife1, %sliderLife1%
Return

Slider2Move:
    Gui, Submit, nohide
    GuiControl,, edtLife2, %sliderLife2%
Return

Slider3Move:
    Gui, Submit, nohide
    GuiControl,, edtLife3, %sliderLife3%
Return

Edit1Modify:
    Gui, Submit, nohide
    GuiControl,, sliderLife1, %edtLife1%
Return

Edit2Modify:
    Gui, Submit, nohide
    GuiControl,, sliderLife2, %edtLife2%
Return

Edit3Modify:
    Gui, Submit, nohide
    GuiControl,, sliderLife3, %edtLife3%
Return

min(num*){
    min := num[1]
	Loop % num.MaxIndex()
		min := (num[A_Index] < min) ? num[A_Index] : min
	return min
}

max(num*){
    max := num[1]
	Loop % num.MaxIndex()
		max := (num[A_Index] > max) ? num[A_Index] : max
	return max
}

^x::
    goto run
Return

abs(a){
    if(a < 0){
        return (-a)
    }
    return a
}

RGB_Euclidian_Distance( c1, c2 ) {
   r1 := c1 >> 16
   g1 := c1 >> 8 & 255
   b1 := c1 & 255
   r2 := c2 >> 16
   g2 := c2 >> 8 & 255
   b2 := c2 & 255
   return Sqrt( (r1-r2)**2 + (g1-g2)**2 + (b1-b2)**2 )
}

isBlack(lifeColor){
    BLUE := 0xFF0000
    RED := 0x0000FF
    BLACK := 0x000000
    
    first := RGB_Euclidian_Distance(lifeColor, RED)
    second := RGB_Euclidian_Distance(lifeColor, BLACK)
    if(first < second){
        return 2
    }
    return 1
}

run:
    WinGetTitle, windowName, A
	IfNotInString, windowName, Tibia
	{
		Return
	}
    
    min_x := min(x1_lifeBar, x2_lifeBar)
    max_x := max(x1_lifeBar, x2_lifeBar)
    min_y := min(y1_lifeBar, y2_lifeBar)
    max_y := max(y1_lifeBar, y2_lifeBar)
    GuiControlGet, Check1
    if(Check1 = 1){
        GuiControlGet, edtLife1
        life1 := % edtLife1
        x_pos := min_x + ((max_x - min_x) * life1) / 100.0
        y_pos := min_y + ((max_y - min_y) * life1) / 100.0
        PixelGetColor, lifeColor, %x_pos%, %y_pos%
        if(isBlack(lifeColor) = 1){
            ; MsgBox, Tem que curar
            GuiControlGet, key1,, cbxKey1
            send {%key1%}
        }
    }
    GuiControlGet, Check2
    if(Check2 = 1){
        GuiControlGet, edtLife2
        life2 := % edtLife2
        x_pos := min_x + ((max_x - min_x) * life2) / 100.0
        y_pos := min_y + ((max_y - min_y) * life2) / 100.0
        ; MsgBox, %x_pos% %y_pos%
        PixelGetColor, lifeColor, %x_pos%, %y_pos%
        if(isBlack(lifeColor) = 1){
            GuiControlGet, key2,, cbxKey2
            send {%key2%}
        }
    }
    GuiControlGet, Check3
    if(Check3 = 1){
        GuiControlGet, edtLife3
        life3 := % edtLife3
        x_pos := min_x + ((max_x - min_x) * life3) / 100.0
        y_pos := min_y + ((max_y - min_y) * life3) / 100.0
        PixelGetColor, lifeColor, %x_pos%, %y_pos%
        if(isBlack(lifeColor) = 1){
            ; MsgBox, Tem que curar
            GuiControlGet, key3,, cbxKey3
            send {%key3%}
        }
    }
    GuiControlGet, checkParalyze
    if(checkParalyze = 1){
        WinGetPos, , , win_width, win_height, A
        ImageSearch, pos_x_image, pos_Y_image, 0, 0, %win_width%, %win_height%, images\paralyze.gif
        if(ErrorLevel = 0){
            GuiControlGet, key_anti_paralyze, , cbxKeyParalyze
            send {%key_anti_paralyze%}
            ; MsgBox, Teste
        }
    }
    
Return

btn_Start:
    if(!(varExist(x1_lifeBar) && varExist(x2_lifeBar))){
        MsgBox, Você precisa setar a posição inicial (Ctrl+1) e final (Ctrl+2) da vida antes.
        return
    }
    Pause, Toggle, 1

    if A_IsPaused {
        GuiControl, , statusBar, O bot se encontra pausado.
        GuiControl, , startPause, Start
        TrayTip, , Bot pausado, , 0x1
    } else {
        GuiControl, , statusBar, O bot está em execução.
        GuiControl, , startPause, Pause
        TrayTip, , Bot iniciado, , 0x1
    }
		
	Return
Return

setTimer:
	GuiControlGet, timer
	if timer = 
	{
		Return
	} else {
        GuiControl, Enabled, startPause
        If !A_IsPaused
            Pause, Toggle, 1
            GuiControl, , startPause, Start
		SetTimer, run, %timer%
	}
Return

GuiEscape:
GuiClose:
    ExitApp
