; Generated by AutoGUI 2.5.4
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Menu menuArquivo, Add, Open...`tCtrl+O, MenuHandler
Menu menuArquivo, Add, Sair`tEsc, MenuHandler
Menu MenuBar, Add, Arquivo, :menuArquivo
Menu menuAjuda, Add, Sobre, MenuHandler
Menu MenuBar, Add, Ajuda, :menuAjuda
Gui Menu, MenuBar

global percentLife1, percentLife2, percentLife3
global x1_lifeBar, x2_lifeBar, y1_lifeBar, y2_lifeBar

Gui Font, s15 Bold, Tahoma
Gui Add, Text, x190 y1 w160 h23 +0x200, Rila Desgraça 2.0
Gui Font
Gui Add, Text, x61 y63 w33 h23 +Disabled +0x200 vtxtKey1, Key 1:
Gui Add, Text, x62 y100 w33 h23 +Disabled +0x200 vtxtKey2, Key 2:
Gui Add, Text, x61 y141 w34 h23 +Disabled +0x200 vtxtKey3, Key 3:
Gui Add, ComboBox, x95 y62 w55 +Disabled +Uppercase vcbxKey1, F1|F2|F3|F4|F5|F6|F7|F8|F9|F10|F11|F12
Gui Add, ComboBox, x95 y99 w55 +Disabled +Uppercase vcbxKey2, F1|F2|F3|F4|F5|F6|F7|F8|F9|F10|F11|F12
Gui Add, ComboBox, x94 y140 w57 +Disabled +Uppercase vcbxKey3, F1|F2|F3|F4|F5|F6|F7|F8|F9|F10|F11|F12
Gui Add, ComboBox, x194 y62 w136 +Disabled vcbxSpell1, Exura|Exura Gran|Exura Ico|Exura Gran Ico
Gui Add, Text, x162 y60 w34 h21 +Disabled +0x200 vtxtSpell1, Spell:
Gui Add, Text, x162 y99 w30 h23 +Disabled +0x200 vtxtSpell2, Spell:
Gui Add, ComboBox, x195 y104 w135 +Disabled vcbxSpell2, Exura|Exura Gran|Exura Ico|Exura Gran Ico
Gui Add, Text, x163 y141 w28 h23 +Disabled +0x200 vtxtSpell3, Spell:
Gui Add, ComboBox, x195 y143 w134 +Disabled vcbxSpell3, Exura|Exura Gran|Exura Ico|Exura Gran Ico
Gui Add, CheckBox, x28 y65 w18 h23 vCheck1 gCheckBox1
Gui Add, CheckBox, x28 y100 w18 h23 vCheck2 gCheckBox2
Gui Add, CheckBox, x28 y140 w26 h23 vCheck3 gCheckBox3
Gui Add, Text, x14 y197 w55 h23 +0x200, Timer (ms):
Gui Add, Edit, x69 y199 w70 h21
Gui Add, Button, x320 y201 w80 h23, &Start
Gui Add, Button, x408 y200 w80 h23, &Save
Gui Add, Slider, x345 y59 w120 h32 +Disabled +Tooltip vsliderLife1 gSlider1Move, 50
Gui Add, Slider, x346 y101 w120 h32 +Disabled +Tooltip vsliderLife2 gSlider2Move, 50
Gui Add, Slider, x346 y142 w120 h32 +Disabled +Tooltip vsliderLife3 gSlider3Move, 50
Gui Add, Edit, x468 y60 w27 h20 +Disabled vedtLife1 gEdit1Modify, 50
Gui Add, Edit, x468 y98 w28 h24 +Disabled vedtLife2 gEdit2Modify, 50
Gui Add, Edit, x469 y142 w26 h22 +Disabled vedtLife3 gEdit3Modify, 50
Gui Show, w526 h235, Window
goto verifyVersion
Return

verifyVersion:
    UrlDownloadToFile, https://raw.githubusercontent.com/Kanchii/AutoHotkey_HealBot/master/version.txt, version_temp.txt
    FileRead, v_tmp, version_temp.txt
    FileRead, vers, version.txt
    if(v_tmp != vers){
        MsgBox, 0x4, Atualização, Tem uma nova versão disponível. Gostaria de atualizar?, 
        IfMsgBox Yes
            goto UpdateProgram
    } else {
        FileDelete, version_temp.txt
    }
Return

UpdateProgram:
    FileRead, v_ants, version.txt
    UrlDownloadToFile, https://raw.githubusercontent.com/Kanchii/AutoHotkey_HealBot/master/version.txt, version.txt
    FileRead, v_depois, version.txt
    StringTrimRight, v_depois, v_depois, 1
    arquivo_Depois := "Rilador_" . v_depois . ".exe"
    MsgBox % arquivo_Depois
    UrlDownloadToFile, https://raw.githubusercontent.com/Kanchii/AutoHotkey_HealBot/master/Rilador.exe, % arquivo_Depois
    FileDelete, version_temp.txt
    arquivo_Deletar := "Rilador_" . v_ants . ".exe"
    FileDelete, % arquivo_Deletar
    ExitApp
Return

MenuHandler:
Return

^1:
    MouseGetPos, x1_LifeBar, y1_LifeBar
Return

^2:
    MouseGetPos, x2_LifeBar, y2_LifeBar
Return

CheckBox1:
    GuiControlGet, Check1
    if(Check1 = 0){
        GuiControl, Disable, txtKey1
        GuiControl, Disable, cbxKey1
        GuiControl, Disable, txtSpell1
        GuiControl, Disable, cbxSpell1
        GuiControl, Disable, sliderLife1
        GuiControl, Disable, edtLife1
    } else {
        GuiControl, Enabled, txtKey1
        GuiControl, Enabled, cbxKey1
        GuiControl, Enabled, txtSpell1
        GuiControl, Enabled, cbxSpell1
        GuiControl, Enabled, sliderLife1
        GuiControl, Enabled, edtLife1
    }
Return


CheckBox2:
    GuiControlGet, Check2
    if(Check2 = 0){
        GuiControl, Disable, txtKey2
        GuiControl, Disable, cbxKey2
        GuiControl, Disable, txtSpell2
        GuiControl, Disable, cbxSpell2
        GuiControl, Disable, sliderLife2
        GuiControl, Disable, edtLife2
    } else {
        GuiControl, Enabled, txtKey2
        GuiControl, Enabled, cbxKey2
        GuiControl, Enabled, txtSpell2
        GuiControl, Enabled, cbxSpell2
        GuiControl, Enabled, sliderLife2
        GuiControl, Enabled, edtLife2
    }
Return


CheckBox3:
    GuiControlGet, Check3
    if(Check3 = 0){
        GuiControl, Disable, txtKey3
        GuiControl, Disable, cbxKey3
        GuiControl, Disable, txtSpell3
        GuiControl, Disable, cbxSpell3
        GuiControl, Disable, sliderLife3
        GuiControl, Disable, edtLife3
    } else {
        GuiControl, Enabled, txtKey3
        GuiControl, Enabled, cbxKey3
        GuiControl, Enabled, txtSpell3
        GuiControl, Enabled, cbxSpell3
        GuiControl, Enabled, sliderLife3
        GuiControl, Enabled, edtLife3
    }
Return

Slider1Move:
    Gui, Submit, nohide
    GuiControl,, edtLife1, %sliderLife1%
Return

Slider2Move:
    Gui, Submit, nohide
    GuiControl,, edtLife2, %sliderLife2%
Return

Slider3Move:
    Gui, Submit, nohide
    GuiControl,, edtLife3, %sliderLife3%
Return

Edit1Modify:
    Gui, Submit, nohide
    GuiControl,, sliderLife1, %edtLife1%
Return

Edit2Modify:
    Gui, Submit, nohide
    GuiControl,, sliderLife2, %edtLife2%
Return

Edit3Modify:
    Gui, Submit, nohide
    GuiControl,, sliderLife3, %edtLife3%
Return

GuiEscape:
GuiClose:
    ExitApp
